export type Hero =
  | "Abathur"
  | "Alarak"
  | "Alexstrasza"
  | "Ana"
  | "Anduin"
  | "Anubarak"
  | "Artanis"
  | "Arthas"
  | "Auriel"
  | "Azmodan"
  | "Blaze"
  | "Brightwing"
  | "Cassia"
  | "Chen"
  | "Cho"
  | "Chromie"
  | "Deathwing"
  | "Deckard"
  | "Dehaka"
  | "Diablo"
  | "DVa"
  | "ETC"
  | "Falstad"
  | "Fenix"
  | "Gall"
  | "Garrosh"
  | "Gazlowe"
  | "Genji"
  | "Greymane"
  | "Guldan"
  | "Hanzo"
  | "Hogger"
  | "Illidan"
  | "Imperius"
  | "Jaina"
  | "Johanna"
  | "Junkrat"
  | "Kaelthas"
  | "KelThuzad"
  | "Kerrigan"
  | "Kharazim"
  | "Leoric"
  | "LiLi"
  | "LiMing"
  | "LtMorales"
  | "Lucio"
  | "Lunara"
  | "Maiev"
  | "Malfurion"
  | "MalGanis"
  | "Malthael"
  | "Medivh"
  | "Mei"
  | "Mephisto"
  | "Muradin"
  | "Murky"
  | "Nazeebo"
  | "Nova"
  | "Orphea"
  | "Probius"
  | "Qhira"
  | "Ragnaros"
  | "Raynor"
  | "Rehgar"
  | "Rexxar"
  | "Samuro"
  | "SgtHammer"
  | "Sonya"
  | "Stitches"
  | "Stukov"
  | "Sylvanas"
  | "Tassadar"
  | "TheButcher"
  | "TheLostVikings"
  | "Thrall"
  | "Tracer"
  | "Tychus"
  | "Tyrael"
  | "Tyrande"
  | "Uther"
  | "Valeera"
  | "Valla"
  | "Varian"
  | "Xalatath"
  | "Xul"
  | "Whitemane"
  | "Yrel"
  | "Zagara"
  | "Zarya"
  | "Zeratul"
  | "Zuljin";

export const Hero = {
  Abathur: "Abathur",
  Alarak: "Alarak",
  Alexstrasza: "Alexstrasza",
  Ana: "Ana",
  Anduin: "Anduin",
  Anubarak: "Anubarak",
  Artanis: "Artanis",
  Arthas: "Arthas",
  Auriel: "Auriel",
  Azmodan: "Azmodan",
  Blaze: "Blaze",
  Brightwing: "Brightwing",
  Cassia: "Cassia",
  Chen: "Chen",
  Cho: "Cho",
  Chromie: "Chromie",
  Deathwing: "Deathwing",
  Deckard: "Deckard",
  Dehaka: "Dehaka",
  Diablo: "Diablo",
  DVa: "DVa",
  ETC: "ETC",
  Falstad: "Falstad",
  Fenix: "Fenix",
  Gall: "Gall",
  Garrosh: "Garrosh",
  Gazlowe: "Gazlowe",
  Genji: "Genji",
  Greymane: "Greymane",
  Guldan: "Guldan",
  Hanzo: "Hanzo",
  Hogger: "Hogger",
  Illidan: "Illidan",
  Imperius: "Imperius",
  Jaina: "Jaina",
  Johanna: "Johanna",
  Junkrat: "Junkrat",
  Kaelthas: "Kaelthas",
  KelThuzad: "KelThuzad",
  Kerrigan: "Kerrigan",
  Kharazim: "Kharazim",
  Leoric: "Leoric",
  LiLi: "LiLi",
  LiMing: "LiMing",
  LtMorales: "LtMorales",
  Lucio: "Lucio",
  Lunara: "Lunara",
  Maiev: "Maiev",
  Malfurion: "Malfurion",
  MalGanis: "MalGanis",
  Malthael: "Malthael",
  Medivh: "Medivh",
  Mei: "Mei",
  Mephisto: "Mephisto",
  Muradin: "Muradin",
  Murky: "Murky",
  Nazeebo: "Nazeebo",
  Nova: "Nova",
  Orphea: "Orphea",
  Probius: "Probius",
  Qhira: "Qhira",
  Ragnaros: "Ragnaros",
  Raynor: "Raynor",
  Rehgar: "Rehgar",
  Rexxar: "Rexxar",
  Samuro: "Samuro",
  SgtHammer: "SgtHammer",
  Sonya: "Sonya",
  Stitches: "Stitches",
  Stukov: "Stukov",
  Sylvanas: "Sylvanas",
  Tassadar: "Tassadar",
  TheButcher: "TheButcher",
  TheLostVikings: "TheLostVikings",
  Thrall: "Thrall",
  Tracer: "Tracer",
  Tychus: "Tychus",
  Tyrael: "Tyrael",
  Tyrande: "Tyrande",
  Uther: "Uther",
  Valeera: "Valeera",
  Valla: "Valla",
  Varian: "Varian",
  Xalatath: "Xalatath",
  Xul: "Xul",
  Whitemane: "Whitemane",
  Yrel: "Yrel",
  Zagara: "Zagara",
  Zarya: "Zarya",
  Zeratul: "Zeratul",
  Zuljin: "Zuljin",
} as const satisfies Record<Hero, Hero>;
