export type HeroRole =
  | "TANKER"
  | "BRUISER"
  | "RANGED_ASSASSIN"
  | "MELEE_ASSASSIN"
  | "HEALER"
  | "SUPPORT";

export const HeroRoleMap = {
  TANKER: "TANKER",
  BRUISER: "BRUISER",
  RANGED_ASSASSIN: "RANGED_ASSASSIN",
  MELEE_ASSASSIN: "MELEE_ASSASSIN",
  HEALER: "HEALER",
  SUPPORT: "SUPPORT",
} as const;
