import { Hero, HeroRole } from "../models";

export interface HeroCatalogEntry {
  readonly nameKo: string;
  readonly image: string;
  readonly icyVeinKey: string;
  readonly role: HeroRole;
}

export const HERO_CATALOG: Record<Hero, HeroCatalogEntry> = {
  Abathur: {
    nameKo: "아바투르",
    image: "/heroes/Abathur.png",
    icyVeinKey: "abathur",
    role: HeroRole.SUB_DEALER,
  },
  Alarak: {
    nameKo: "알라라크",
    image: "/heroes/Alarak.png",
    icyVeinKey: "alarak",
    role: HeroRole.SUB_DEALER,
  },
  Alexstrasza: {
    nameKo: "알렉스트라자",
    image: "/heroes/Alexstrasza.png",
    icyVeinKey: "alexstrasza",
    role: HeroRole.HEALER,
  },
  Ana: {
    nameKo: "아나",
    image: "/heroes/Ana.png",
    icyVeinKey: "ana",
    role: HeroRole.HEALER,
  },
  Anduin: {
    nameKo: "안두인",
    image: "/heroes/Anduin.png",
    icyVeinKey: "anduin",
    role: HeroRole.HEALER,
  },
  Anubarak: {
    nameKo: "아눕아락",
    image: "/heroes/Anubarak.png",
    icyVeinKey: "anubarak",
    role: HeroRole.TANKER,
  },
  Artanis: {
    nameKo: "아르타니스",
    image: "/heroes/Artanis.png",
    icyVeinKey: "artanis",
    role: HeroRole.OFFLANER,
  },
  Arthas: {
    nameKo: "아서스",
    image: "/heroes/Arthas.png",
    icyVeinKey: "arthas",
    role: HeroRole.TANKER,
  },
  Auriel: {
    nameKo: "아우리엘",
    image: "/heroes/Auriel.png",
    icyVeinKey: "auriel",
    role: HeroRole.HEALER,
  },
  Azmodan: {
    nameKo: "아즈모단",
    image: "/heroes/Azmodan.png",
    icyVeinKey: "azmodan",
    role: HeroRole.SUB_DEALER,
  },
  Blaze: {
    nameKo: "블레이즈",
    image: "/heroes/Blaze.png",
    icyVeinKey: "blaze",
    role: HeroRole.TANKER,
  },
  Brightwing: {
    nameKo: "빛나래",
    image: "/heroes/Brightwing.png",
    icyVeinKey: "brightwing",
    role: HeroRole.HEALER,
  },
  Cassia: {
    nameKo: "카시아",
    image: "/heroes/Cassia.png",
    icyVeinKey: "cassia",
    role: HeroRole.MAIN_DEALER,
  },
  Chen: {
    nameKo: "첸",
    image: "/heroes/Chen.png",
    icyVeinKey: "chen",
    role: HeroRole.OFFLANER,
  },
  Cho: {
    nameKo: "초",
    image: "/heroes/Cho.png",
    icyVeinKey: "cho",
    role: HeroRole.TANKER,
  },
  Chromie: {
    nameKo: "크로미",
    image: "/heroes/Chromie.png",
    icyVeinKey: "chromie",
    role: HeroRole.SUB_DEALER,
  },
  Deathwing: {
    nameKo: "데스윙",
    image: "/heroes/Deathwing.png",
    icyVeinKey: "deathwing",
    role: HeroRole.OFFLANER,
  },
  Deckard: {
    nameKo: "데커드",
    image: "/heroes/Deckard.png",
    icyVeinKey: "deckard-cain",
    role: HeroRole.HEALER,
  },
  Dehaka: {
    nameKo: "데하카",
    image: "/heroes/Dehaka.png",
    icyVeinKey: "dehaka",
    role: HeroRole.OFFLANER,
  },
  Diablo: {
    nameKo: "디아블로",
    image: "/heroes/Diablo.png",
    icyVeinKey: "diablo",
    role: HeroRole.TANKER,
  },
  DVa: {
    nameKo: "D.Va",
    image: "/heroes/DVa.png",
    icyVeinKey: "dva",
    role: HeroRole.OFFLANER,
  },
  ETC: {
    nameKo: "정예 타우렌 족장",
    image: "/heroes/ETC.png",
    icyVeinKey: "e-t-c",
    role: HeroRole.TANKER,
  },
  Falstad: {
    nameKo: "폴스타트",
    image: "/heroes/Falstad.png",
    icyVeinKey: "falstad",
    role: HeroRole.MAIN_DEALER,
  },
  Fenix: {
    nameKo: "페닉스",
    image: "/heroes/Fenix.png",
    icyVeinKey: "fenix",
    role: HeroRole.SUB_DEALER,
  },
  Gall: {
    nameKo: "갈",
    image: "/heroes/Gall.png",
    icyVeinKey: "gall",
    role: HeroRole.SUB_DEALER,
  },
  Garrosh: {
    nameKo: "가로쉬",
    image: "/heroes/Garrosh.png",
    icyVeinKey: "garrosh",
    role: HeroRole.TANKER,
  },
  Gazlowe: {
    nameKo: "가즈로",
    image: "/heroes/Gazlowe.png",
    icyVeinKey: "gazlowe",
    role: HeroRole.OFFLANER,
  },
  Genji: {
    nameKo: "겐지",
    image: "/heroes/Genji.png",
    icyVeinKey: "genji",
    role: HeroRole.SUB_DEALER,
  },
  Greymane: {
    nameKo: "그레이메인",
    image: "/heroes/Greymane.png",
    icyVeinKey: "greymane",
    role: HeroRole.MAIN_DEALER,
  },
  Guldan: {
    nameKo: "굴단",
    image: "/heroes/Guldan.png",
    icyVeinKey: "guldan",
    role: HeroRole.SUB_DEALER,
  },
  Hanzo: {
    nameKo: "한조",
    image: "/heroes/Hanzo.png",
    icyVeinKey: "hanzo",
    role: HeroRole.MAIN_DEALER,
  },
  Hogger: {
    nameKo: "들창코",
    image: "/heroes/Hogger.png",
    icyVeinKey: "hogger",
    role: HeroRole.OFFLANER,
  },
  Illidan: {
    nameKo: "일리단",
    image: "/heroes/Illidan.png",
    icyVeinKey: "illidan",
    role: HeroRole.OFFLANER,
  },
  Imperius: {
    nameKo: "임페리우스",
    image: "/heroes/Imperius.png",
    icyVeinKey: "imperius",
    role: HeroRole.OFFLANER,
  },
  Jaina: {
    nameKo: "제이나",
    image: "/heroes/Jaina.png",
    icyVeinKey: "jaina",
    role: HeroRole.SUB_DEALER,
  },
  Johanna: {
    nameKo: "요한나",
    image: "/heroes/Johanna.png",
    icyVeinKey: "johanna",
    role: HeroRole.TANKER,
  },
  Junkrat: {
    nameKo: "정크랫",
    image: "/heroes/Junkrat.png",
    icyVeinKey: "junkrat",
    role: HeroRole.SUB_DEALER,
  },
  Kaelthas: {
    nameKo: "캘타스",
    image: "/heroes/Kaelthas.png",
    icyVeinKey: "kaelthas",
    role: HeroRole.SUB_DEALER,
  },
  KelThuzad: {
    nameKo: "켈투자드",
    image: "/heroes/KelThuzad.png",
    icyVeinKey: "kel-thuzad",
    role: HeroRole.SUB_DEALER,
  },
  Kerrigan: {
    nameKo: "케리건",
    image: "/heroes/Kerrigan.png",
    icyVeinKey: "kerrigan",
    role: HeroRole.SUB_DEALER,
  },
  Kharazim: {
    nameKo: "카라짐",
    image: "/heroes/Kharazim.png",
    icyVeinKey: "kharazim",
    role: HeroRole.HEALER,
  },
  Leoric: {
    nameKo: "레오릭",
    image: "/heroes/Leoric.png",
    icyVeinKey: "leoric",
    role: HeroRole.OFFLANER,
  },
  LiLi: {
    nameKo: "리 리",
    image: "/heroes/LiLi.png",
    icyVeinKey: "li-li",
    role: HeroRole.HEALER,
  },
  LiMing: {
    nameKo: "리밍",
    image: "/heroes/LiMing.png",
    icyVeinKey: "li-ming",
    role: HeroRole.SUB_DEALER,
  },
  LtMorales: {
    nameKo: "모랄레스 중위",
    image: "/heroes/LtMorales.png",
    icyVeinKey: "lt-morales",
    role: HeroRole.HEALER,
  },
  Lucio: {
    nameKo: "루시우",
    image: "/heroes/Lucio.png",
    icyVeinKey: "lucio",
    role: HeroRole.HEALER,
  },
  Lunara: {
    nameKo: "루나라",
    image: "/heroes/Lunara.png",
    icyVeinKey: "lunara",
    role: HeroRole.SUB_DEALER,
  },
  Maiev: {
    nameKo: "마이에브",
    image: "/heroes/Maiev.png",
    icyVeinKey: "maiev",
    role: HeroRole.SUB_DEALER,
  },
  Malfurion: {
    nameKo: "말퓨리온",
    image: "/heroes/Malfurion.png",
    icyVeinKey: "malfurion",
    role: HeroRole.HEALER,
  },
  MalGanis: {
    nameKo: "말가니스",
    image: "/heroes/MalGanis.png",
    icyVeinKey: "malganis",
    role: HeroRole.TANKER,
  },
  Malthael: {
    nameKo: "말티엘",
    image: "/heroes/Malthael.png",
    icyVeinKey: "malthael",
    role: HeroRole.OFFLANER,
  },
  Medivh: {
    nameKo: "메디브",
    image: "/heroes/Medivh.png",
    icyVeinKey: "medivh",
    role: HeroRole.SUB_DEALER,
  },
  Mei: {
    nameKo: "메이",
    image: "/heroes/Mei.png",
    icyVeinKey: "mei",
    role: HeroRole.TANKER,
  },
  Mephisto: {
    nameKo: "메피스토",
    image: "/heroes/Mephisto.png",
    icyVeinKey: "mephisto",
    role: HeroRole.SUB_DEALER,
  },
  Muradin: {
    nameKo: "무라딘",
    image: "/heroes/Muradin.png",
    icyVeinKey: "muradin",
    role: HeroRole.TANKER,
  },
  Murky: {
    nameKo: "머키",
    image: "/heroes/Murky.png",
    icyVeinKey: "murky",
    role: HeroRole.OFFLANER,
  },
  Nazeebo: {
    nameKo: "나지보",
    image: "/heroes/Nazeebo.png",
    icyVeinKey: "nazeebo",
    role: HeroRole.SUB_DEALER,
  },
  Nova: {
    nameKo: "노바",
    image: "/heroes/Nova.png",
    icyVeinKey: "nova",
    role: HeroRole.SUB_DEALER,
  },
  Orphea: {
    nameKo: "오르피아",
    image: "/heroes/Orphea.png",
    icyVeinKey: "orphea",
    role: HeroRole.SUB_DEALER,
  },
  Probius: {
    nameKo: "프로비우스",
    image: "/heroes/Probius.png",
    icyVeinKey: "probius",
    role: HeroRole.SUB_DEALER,
  },
  Qhira: {
    nameKo: "키히라",
    image: "/heroes/Qhira.png",
    icyVeinKey: "qhira",
    role: HeroRole.SUB_DEALER,
  },
  Ragnaros: {
    nameKo: "라그나로스",
    image: "/heroes/Ragnaros.png",
    icyVeinKey: "ragnaros",
    role: HeroRole.OFFLANER,
  },
  Raynor: {
    nameKo: "레이너",
    image: "/heroes/Raynor.png",
    icyVeinKey: "raynor",
    role: HeroRole.MAIN_DEALER,
  },
  Rehgar: {
    nameKo: "레가르",
    image: "/heroes/Rehgar.png",
    icyVeinKey: "rehgar",
    role: HeroRole.HEALER,
  },
  Rexxar: {
    nameKo: "렉사르",
    image: "/heroes/Rexxar.png",
    icyVeinKey: "rexxar",
    role: HeroRole.OFFLANER,
  },
  Samuro: {
    nameKo: "사무로",
    image: "/heroes/Samuro.png",
    icyVeinKey: "samuro",
    role: HeroRole.SUB_DEALER,
  },
  SgtHammer: {
    nameKo: "해머 상사",
    image: "/heroes/SgtHammer.png",
    icyVeinKey: "sgt-hammer",
    role: HeroRole.MAIN_DEALER,
  },
  Sonya: {
    nameKo: "소냐",
    image: "/heroes/Sonya.png",
    icyVeinKey: "sonya",
    role: HeroRole.OFFLANER,
  },
  Stitches: {
    nameKo: "누더기",
    image: "/heroes/Stitches.png",
    icyVeinKey: "stitches",
    role: HeroRole.TANKER,
  },
  Stukov: {
    nameKo: "스투코프",
    image: "/heroes/Stukov.png",
    icyVeinKey: "stukov",
    role: HeroRole.HEALER,
  },
  Sylvanas: {
    nameKo: "실바나스",
    image: "/heroes/Sylvanas.png",
    icyVeinKey: "sylvanas",
    role: HeroRole.MAIN_DEALER,
  },
  Tassadar: {
    nameKo: "태사다르",
    image: "/heroes/Tassadar.png",
    icyVeinKey: "tassadar",
    role: HeroRole.SUB_DEALER,
  },
  TheButcher: {
    nameKo: "도살자",
    image: "/heroes/TheButcher.png",
    icyVeinKey: "the-butcher",
    role: HeroRole.SUB_DEALER,
  },
  TheLostVikings: {
    nameKo: "길 잃은 바이킹",
    image: "/heroes/TheLostVikings.png",
    icyVeinKey: "the-lost-vikings",
    role: HeroRole.OFFLANER,
  },
  Thrall: {
    nameKo: "스랄",
    image: "/heroes/Thrall.png",
    icyVeinKey: "thrall",
    role: HeroRole.OFFLANER,
  },
  Tracer: {
    nameKo: "트레이서",
    image: "/heroes/Tracer.png",
    icyVeinKey: "tracer",
    role: HeroRole.SUB_DEALER,
  },
  Tychus: {
    nameKo: "타이커스",
    image: "/heroes/Tychus.png",
    icyVeinKey: "tychus",
    role: HeroRole.MAIN_DEALER,
  },
  Tyrael: {
    nameKo: "티리엘",
    image: "/heroes/Tyrael.png",
    icyVeinKey: "tyrael",
    role: HeroRole.TANKER,
  },
  Tyrande: {
    nameKo: "티란데",
    image: "/heroes/Tyrande.png",
    icyVeinKey: "tyrande",
    role: HeroRole.HEALER,
  },
  Uther: {
    nameKo: "우서",
    image: "/heroes/Uther.png",
    icyVeinKey: "uther",
    role: HeroRole.HEALER,
  },
  Valeera: {
    nameKo: "발리라",
    image: "/heroes/Valeera.png",
    icyVeinKey: "valeera",
    role: HeroRole.SUB_DEALER,
  },
  Valla: {
    nameKo: "발라",
    image: "/heroes/Valla.png",
    icyVeinKey: "valla",
    role: HeroRole.MAIN_DEALER,
  },
  Varian: {
    nameKo: "바리안",
    image: "/heroes/Varian.png",
    icyVeinKey: "varian",
    role: HeroRole.TANKER,
  },
  Xalatath: {
    nameKo: "잘아타스",
    image: "/heroes/Xalatath.png",
    icyVeinKey: "xalatath",
    role: HeroRole.SUB_DEALER,
  },
  Xul: {
    nameKo: "줄",
    image: "/heroes/Xul.png",
    icyVeinKey: "xul",
    role: HeroRole.OFFLANER,
  },
  Whitemane: {
    nameKo: "화이트메인",
    image: "/heroes/Whitemane.png",
    icyVeinKey: "whitemane",
    role: HeroRole.HEALER,
  },
  Yrel: {
    nameKo: "이렐",
    image: "/heroes/Yrel.png",
    icyVeinKey: "yrel",
    role: HeroRole.OFFLANER,
  },
  Zagara: {
    nameKo: "자가라",
    image: "/heroes/Zagara.png",
    icyVeinKey: "zagara",
    role: HeroRole.SUB_DEALER,
  },
  Zarya: {
    nameKo: "자리야",
    image: "/heroes/Zarya.png",
    icyVeinKey: "zarya",
    role: HeroRole.SUB_DEALER,
  },
  Zeratul: {
    nameKo: "제라툴",
    image: "/heroes/Zeratul.png",
    icyVeinKey: "zeratul",
    role: HeroRole.SUB_DEALER,
  },
  Zuljin: {
    nameKo: "줄진",
    image: "/heroes/Zuljin.png",
    icyVeinKey: "zuljin",
    role: HeroRole.MAIN_DEALER,
  },
} as const;
