import type { Hero } from "../models";
import { HeroRoles, type HeroRole } from "../models/hero-role";

export interface HeroCatalogEntry {
  readonly nameKo: string;
  readonly image: string;
  readonly legacyImage: string;
  readonly role: HeroRole;
}

export const HERO_CATALOG = {
  Abathur: {
    nameKo: "아바투르",
    image: "/heroes/Abathur.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/abathur.png",
    role: HeroRoles.SUB_DEALER,
  },
  Alarak: {
    nameKo: "알라라크",
    image: "/heroes/Alarak.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/alarak.png",
    role: HeroRoles.SUB_DEALER,
  },
  Alexstrasza: {
    nameKo: "알렉스트라자",
    image: "/heroes/Alexstrasza.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/alexstrasza.png",
    role: HeroRoles.HEALER,
  },
  Ana: {
    nameKo: "아나",
    image: "/heroes/Ana.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/ana.png",
    role: HeroRoles.HEALER,
  },
  Anduin: {
    nameKo: "안두인",
    image: "/heroes/Anduin.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/anduin.png",
    role: HeroRoles.HEALER,
  },
  Anubarak: {
    nameKo: "아눕아락",
    image: "/heroes/Anubarak.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/anubarak.png",
    role: HeroRoles.TANKER,
  },
  Artanis: {
    nameKo: "아르타니스",
    image: "/heroes/Artanis.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/artanis.png",
    role: HeroRoles.OFFLANER,
  },
  Arthas: {
    nameKo: "아서스",
    image: "/heroes/Arthas.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/arthas.png",
    role: HeroRoles.TANKER,
  },
  Auriel: {
    nameKo: "아우리엘",
    image: "/heroes/Auriel.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/auriel.png",
    role: HeroRoles.HEALER,
  },
  Azmodan: {
    nameKo: "아즈모단",
    image: "/heroes/Azmodan.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/azmodan.png",
    role: HeroRoles.SUB_DEALER,
  },
  Blaze: {
    nameKo: "블레이즈",
    image: "/heroes/Blaze.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/blaze.png",
    role: HeroRoles.TANKER,
  },
  Brightwing: {
    nameKo: "빛나래",
    image: "/heroes/Brightwing.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/brightwing.png",
    role: HeroRoles.HEALER,
  },
  Cassia: {
    nameKo: "카시아",
    image: "/heroes/Cassia.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/cassia.png",
    role: HeroRoles.MAIN_DEALER,
  },
  Chen: {
    nameKo: "첸",
    image: "/heroes/Chen.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/chen.png",
    role: HeroRoles.OFFLANER,
  },
  Cho: {
    nameKo: "초",
    image: "/heroes/Cho.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/cho.png",
    role: HeroRoles.TANKER,
  },
  Chromie: {
    nameKo: "크로미",
    image: "/heroes/Chromie.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/chromie.png",
    role: HeroRoles.SUB_DEALER,
  },
  Deathwing: {
    nameKo: "데스윙",
    image: "/heroes/Deathwing.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/deathwing.png",
    role: HeroRoles.OFFLANER,
  },
  Deckard: {
    nameKo: "데커드",
    image: "/heroes/Deckard.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/deckard.png",
    role: HeroRoles.HEALER,
  },
  Dehaka: {
    nameKo: "데하카",
    image: "/heroes/Dehaka.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/dehaka.png",
    role: HeroRoles.OFFLANER,
  },
  Diablo: {
    nameKo: "디아블로",
    image: "/heroes/Diablo.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/diablo.png",
    role: HeroRoles.TANKER,
  },
  DVa: {
    nameKo: "D.Va",
    image: "/heroes/DVa.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/dva.png",
    role: HeroRoles.OFFLANER,
  },
  ETC: {
    nameKo: "정예 타우렌 족장",
    image: "/heroes/ETC.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/etc.png",
    role: HeroRoles.TANKER,
  },
  Falstad: {
    nameKo: "폴스타트",
    image: "/heroes/Falstad.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/falstad.png",
    role: HeroRoles.MAIN_DEALER,
  },
  Fenix: {
    nameKo: "페닉스",
    image: "/heroes/Fenix.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/fenix.png",
    role: HeroRoles.SUB_DEALER,
  },
  Gall: {
    nameKo: "갈",
    image: "/heroes/Gall.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/gall.png",
    role: HeroRoles.SUB_DEALER,
  },
  Garrosh: {
    nameKo: "가로쉬",
    image: "/heroes/Garrosh.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/garrosh.png",
    role: HeroRoles.TANKER,
  },
  Gazlowe: {
    nameKo: "가즈로",
    image: "/heroes/Gazlowe.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/gazlowe.png",
    role: HeroRoles.OFFLANER,
  },
  Genji: {
    nameKo: "겐지",
    image: "/heroes/Genji.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/genji.png",
    role: HeroRoles.SUB_DEALER,
  },
  Greymane: {
    nameKo: "그레이메인",
    image: "/heroes/Greymane.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/greymane.png",
    role: HeroRoles.MAIN_DEALER,
  },
  Guldan: {
    nameKo: "굴단",
    image: "/heroes/Guldan.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/guldan.png",
    role: HeroRoles.SUB_DEALER,
  },
  Hanzo: {
    nameKo: "한조",
    image: "/heroes/Hanzo.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/hanzo.png",
    role: HeroRoles.MAIN_DEALER,
  },
  Hogger: {
    nameKo: "들창코",
    image: "/heroes/Hogger.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/hogger.png",
    role: HeroRoles.OFFLANER,
  },
  Illidan: {
    nameKo: "일리단",
    image: "/heroes/Illidan.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/illidan.png",
    role: HeroRoles.OFFLANER,
  },
  Imperius: {
    nameKo: "임페리우스",
    image: "/heroes/Imperius.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/imperius.png",
    role: HeroRoles.OFFLANER,
  },
  Jaina: {
    nameKo: "제이나",
    image: "/heroes/Jaina.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/jaina.png",
    role: HeroRoles.SUB_DEALER,
  },
  Johanna: {
    nameKo: "요한나",
    image: "/heroes/Johanna.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/johanna.png",
    role: HeroRoles.TANKER,
  },
  Junkrat: {
    nameKo: "정크랫",
    image: "/heroes/Junkrat.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/junkrat.png",
    role: HeroRoles.SUB_DEALER,
  },
  Kaelthas: {
    nameKo: "캘타스",
    image: "/heroes/Kaelthas.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/kaelthas.png",
    role: HeroRoles.SUB_DEALER,
  },
  KelThuzad: {
    nameKo: "켈투자드",
    image: "/heroes/KelThuzad.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/kelthuzad.png",
    role: HeroRoles.SUB_DEALER,
  },
  Kerrigan: {
    nameKo: "케리건",
    image: "/heroes/Kerrigan.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/kerrigan.png",
    role: HeroRoles.SUB_DEALER,
  },
  Kharazim: {
    nameKo: "카라짐",
    image: "/heroes/Kharazim.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/kharazim.png",
    role: HeroRoles.HEALER,
  },
  Leoric: {
    nameKo: "레오릭",
    image: "/heroes/Leoric.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/leoric.png",
    role: HeroRoles.OFFLANER,
  },
  LiLi: {
    nameKo: "리 리",
    image: "/heroes/LiLi.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/li-li.png",
    role: HeroRoles.HEALER,
  },
  LiMing: {
    nameKo: "리밍",
    image: "/heroes/LiMing.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/li-ming.png",
    role: HeroRoles.SUB_DEALER,
  },
  LtMorales: {
    nameKo: "모랄레스 중위",
    image: "/heroes/LtMorales.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/lt-morales.png",
    role: HeroRoles.HEALER,
  },
  Lucio: {
    nameKo: "루시우",
    image: "/heroes/Lucio.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/lucio.png",
    role: HeroRoles.HEALER,
  },
  Lunara: {
    nameKo: "루나라",
    image: "/heroes/Lunara.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/lunara.png",
    role: HeroRoles.SUB_DEALER,
  },
  Maiev: {
    nameKo: "마이에브",
    image: "/heroes/Maiev.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/maiev.png",
    role: HeroRoles.SUB_DEALER,
  },
  Malfurion: {
    nameKo: "말퓨리온",
    image: "/heroes/Malfurion.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/malfurion.png",
    role: HeroRoles.HEALER,
  },
  MalGanis: {
    nameKo: "말가니스",
    image: "/heroes/MalGanis.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/malganis.png",
    role: HeroRoles.TANKER,
  },
  Malthael: {
    nameKo: "말티엘",
    image: "/heroes/Malthael.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/malthael.png",
    role: HeroRoles.OFFLANER,
  },
  Medivh: {
    nameKo: "메디브",
    image: "/heroes/Medivh.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/medivh.png",
    role: HeroRoles.SUB_DEALER,
  },
  Mei: {
    nameKo: "메이",
    image: "/heroes/Mei.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/mei.png",
    role: HeroRoles.TANKER,
  },
  Mephisto: {
    nameKo: "메피스토",
    image: "/heroes/Mephisto.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/mephisto.png",
    role: HeroRoles.SUB_DEALER,
  },
  Muradin: {
    nameKo: "무라딘",
    image: "/heroes/Muradin.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/muradin.png",
    role: HeroRoles.TANKER,
  },
  Murky: {
    nameKo: "머키",
    image: "/heroes/Murky.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/murky.png",
    role: HeroRoles.OFFLANER,
  },
  Nazeebo: {
    nameKo: "나지보",
    image: "/heroes/Nazeebo.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/nazeebo.png",
    role: HeroRoles.SUB_DEALER,
  },
  Nova: {
    nameKo: "노바",
    image: "/heroes/Nova.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/nova.png",
    role: HeroRoles.SUB_DEALER,
  },
  Orphea: {
    nameKo: "오르피아",
    image: "/heroes/Orphea.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/orphea.png",
    role: HeroRoles.SUB_DEALER,
  },
  Probius: {
    nameKo: "프로비우스",
    image: "/heroes/Probius.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/probius.png",
    role: HeroRoles.SUB_DEALER,
  },
  Qhira: {
    nameKo: "키히라",
    image: "/heroes/Qhira.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/qhira.png",
    role: HeroRoles.SUB_DEALER,
  },
  Ragnaros: {
    nameKo: "라그나로스",
    image: "/heroes/Ragnaros.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/ragnaros.png",
    role: HeroRoles.OFFLANER,
  },
  Raynor: {
    nameKo: "레이너",
    image: "/heroes/Raynor.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/raynor.png",
    role: HeroRoles.MAIN_DEALER,
  },
  Rehgar: {
    nameKo: "레가르",
    image: "/heroes/Rehgar.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/rehgar.png",
    role: HeroRoles.HEALER,
  },
  Rexxar: {
    nameKo: "렉사르",
    image: "/heroes/Rexxar.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/rexxar.png",
    role: HeroRoles.OFFLANER,
  },
  Samuro: {
    nameKo: "사무로",
    image: "/heroes/Samuro.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/samuro.png",
    role: HeroRoles.SUB_DEALER,
  },
  SgtHammer: {
    nameKo: "해머 상사",
    image: "/heroes/SgtHammer.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/sgt-hammer.png",
    role: HeroRoles.MAIN_DEALER,
  },
  Sonya: {
    nameKo: "소냐",
    image: "/heroes/Sonya.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/sonya.png",
    role: HeroRoles.OFFLANER,
  },
  Stitches: {
    nameKo: "누더기",
    image: "/heroes/Stitches.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/stitches.png",
    role: HeroRoles.TANKER,
  },
  Stukov: {
    nameKo: "스투코프",
    image: "/heroes/Stukov.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/stukov.png",
    role: HeroRoles.HEALER,
  },
  Sylvanas: {
    nameKo: "실바나스",
    image: "/heroes/Sylvanas.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/sylvanas.png",
    role: HeroRoles.MAIN_DEALER,
  },
  Tassadar: {
    nameKo: "태사다르",
    image: "/heroes/Tassadar.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/tassadar.png",
    role: HeroRoles.SUB_DEALER,
  },
  TheButcher: {
    nameKo: "도살자",
    image: "/heroes/TheButcher.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/the-butcher.png",
    role: HeroRoles.SUB_DEALER,
  },
  TheLostVikings: {
    nameKo: "길 잃은 바이킹",
    image: "/heroes/TheLostVikings.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/the-lost-vikings.png",
    role: HeroRoles.OFFLANER,
  },
  Thrall: {
    nameKo: "스랄",
    image: "/heroes/Thrall.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/thrall.png",
    role: HeroRoles.OFFLANER,
  },
  Tracer: {
    nameKo: "트레이서",
    image: "/heroes/Tracer.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/tracer.png",
    role: HeroRoles.SUB_DEALER,
  },
  Tychus: {
    nameKo: "타이커스",
    image: "/heroes/Tychus.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/tychus.png",
    role: HeroRoles.MAIN_DEALER,
  },
  Tyrael: {
    nameKo: "티리엘",
    image: "/heroes/Tyrael.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/tyrael.png",
    role: HeroRoles.TANKER,
  },
  Tyrande: {
    nameKo: "티란데",
    image: "/heroes/Tyrande.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/tyrande.png",
    role: HeroRoles.HEALER,
  },
  Uther: {
    nameKo: "우서",
    image: "/heroes/Uther.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/uther.png",
    role: HeroRoles.HEALER,
  },
  Valeera: {
    nameKo: "발리라",
    image: "/heroes/Valeera.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/valeera.png",
    role: HeroRoles.SUB_DEALER,
  },
  Valla: {
    nameKo: "발라",
    image: "/heroes/Valla.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/valla.png",
    role: HeroRoles.MAIN_DEALER,
  },
  Varian: {
    nameKo: "바리안",
    image: "/heroes/Varian.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/varian.png",
    role: HeroRoles.TANKER,
  },
  Xul: {
    nameKo: "줄",
    image: "/heroes/Xul.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/xul.png",
    role: HeroRoles.OFFLANER,
  },
  Whitemane: {
    nameKo: "화이트메인",
    image: "/heroes/Whitemane.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/whitemane.png",
    role: HeroRoles.HEALER,
  },
  Yrel: {
    nameKo: "이렐",
    image: "/heroes/Yrel.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/yrel.png",
    role: HeroRoles.OFFLANER,
  },
  Zagara: {
    nameKo: "자가라",
    image: "/heroes/Zagara.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/zagara.png",
    role: HeroRoles.SUB_DEALER,
  },
  Zarya: {
    nameKo: "자리야",
    image: "/heroes/Zarya.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/zarya.png",
    role: HeroRoles.SUB_DEALER,
  },
  Zeratul: {
    nameKo: "제라툴",
    image: "/heroes/Zeratul.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/zeratul.png",
    role: HeroRoles.SUB_DEALER,
  },
  Zuljin: {
    nameKo: "줄진",
    image: "/heroes/Zuljin.png",
    legacyImage: "https://nexuscompendium.com/images/portraits/zuljin.png",
    role: HeroRoles.MAIN_DEALER,
  },
} as const satisfies Record<Hero, HeroCatalogEntry>;
