import { Hero } from "../models/hero";

export const HeroMap: Record<Hero, string> = {
  Abathur: "아바투르",
  Alarak: "알라라크",
  Alexstrasza: "알렉스트라자",
  Ana: "아나",
  Anduin: "안두인",
  Anubarak: "아눕아락",
  Artanis: "아르타니스",
  Arthas: "아서스",
  Auriel: "아우리엘",
  Azmodan: "아즈모단",
  Blaze: "블레이즈",
  Brightwing: "빛나래",
  Cassia: "카시아",
  Chen: "첸",
  Cho: "초",
  Chromie: "크로미",
  Deathwing: "데스윙",
  Deckard: "데커드",
  Dehaka: "데하카",
  Diablo: "디아블로",
  DVa: "D.Va",
  ETC: "정예 타우렌 족장",
  Falstad: "폴스타트",
  Fenix: "페닉스",
  Gall: "갈",
  Garrosh: "가로쉬",
  Gazlowe: "가즈로",
  Genji: "겐지",
  Greymane: "그레이메인",
  Guldan: "굴단",
  Hanzo: "한조",
  Hogger: "들창코",
  Illidan: "일리단",
  Imperius: "임페리우스",
  Jaina: "제이나",
  Johanna: "요한나",
  Junkrat: "정크랫",
  Kaelthas: "캘타스",
  KelThuzad: "켈투자드",
  Kerrigan: "케리건",
  Kharazim: "카라짐",
  Leoric: "레오릭",
  LiLi: "리 리",
  LiMing: "리밍",
  LtMorales: "모랄레스 중위",
  Lucio: "루시우",
  Lunara: "루나라",
  Maiev: "마이에브",
  Malfurion: "말퓨리온",
  MalGanis: "말가니스",
  Malthael: "말티엘",
  Medivh: "메디브",
  Mei: "메이",
  Mephisto: "메피스토",
  Muradin: "무라딘",
  Murky: "머키",
  Nazeebo: "나지보",
  Nova: "노바",
  Orphea: "오르피아",
  Probius: "프로비우스",
  Qhira: "키히라",
  Ragnaros: "라그나로스",
  Raynor: "레이너",
  Rehgar: "레가르",
  Rexxar: "렉사르",
  Samuro: "사무로",
  SgtHammer: "해머 상사",
  Sonya: "소냐",
  Stitches: "누더기",
  Stukov: "스투코프",
  Sylvanas: "실바나스",
  Tassadar: "태사다르",
  TheButcher: "도살자",
  TheLostVikings: "길 잃은 바이킹",
  Thrall: "스랄",
  Tracer: "트레이서",
  Tychus: "타이커스",
  Tyrael: "티리엘",
  Tyrande: "티란데",
  Uther: "우서",
  Valeera: "발리라",
  Valla: "발라",
  Varian: "바리안",
  Xul: "줄",
  Whitemane: "화이트메인",
  Yrel: "이렐",
  Zagara: "자가라",
  Zarya: "자리야",
  Zeratul: "제라툴",
  Zuljin: "줄진",
};
